version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  
  api:
    build:
      context: ./api
    container_name: api
    links:
      - db:postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    ports:
      - '8080:8080'

  web:
    build:
      context: ./web
    depends_on:
      - api
    container_name: web
    ports:
      - '80:4200'

volumes:
  database:
    driver: local